console.log(sprintf("Hello, %s!", "world"));
console.log(sprintf("My name is %s and I am %s.", "John", "a developer"));
console.log(sprintf("Number: %d", 42));
console.log(sprintf("Padded Number: %04d", 42));
console.log(sprintf("Negative Number: %d", -42));
console.log(sprintf("Pi: %.2f", 3.14159));
console.log(sprintf("Scientific: %.4e", 123.456789));
console.log(sprintf("Width and Precision: %8.2f", 123.456));
console.log(sprintf("Name: %(name)s, Age: %(age)d", {name: "Alice", age: 30}));
console.log(sprintf("Coordinates: x = %(x).2f, y = %(y).2f", {x: 12.345, y: 67.890}));
console.log(sprintf("Order: %1$s, %3$s, %2$s", "first", "second", "third"));
console.log(sprintf("Order: %2$d, %1$d", 10, 20));
console.log(sprintf("Object: %s", {key: "value"}));
console.log(sprintf("Nested Object: %s", {key: {nestedKey: "nestedValue"}}));
console.log(sprintf("100%% Complete"));
console.log(sprintf("Discount: %d%%", 20));
console.log(sprintf("String: %s, Integer: %d, Float: %.2f", "test", 123, 45.678));
console.log(sprintf("%2$s costs $%1$.2f", 12.34, "Apple"));
console.log(sprintf("Padded: [%10s]", "pad"));
console.log(sprintf("Zero-padded: [%010d]", 42));
console.log(sprintf("No arguments: %s", undefined));
console.log(sprintf("Null value: %s", null));
console.log(sprintf("Array: %s", [1, 2, 3]));
console.log(sprintf("Boolean: %s", true));
console.log(vsprintf("Hello, %s!", ["world"]));
console.log(vsprintf("Number: %04d", [42]));
console.log(vsprintf("Pi: %.2f", [3.14159]));
console.log(sprintf("Custom padding: [%010d]", 42));
console.log(sprintf("Space padding: [%10s]", "test"));